apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rate-limiter-chart.fullname" . }}
  labels:
    {{- include "rate-limiter-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rate-limiter-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rate-limiter-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rate-limiter-chart.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: {{ .Values.init.name }}
        image: {{ .Values.init.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: REDIS_HOST
          value: "{{ .Values.redis.fullnameOverride }}-master"
        - name: REDIS_PORT
          value: "{{ .Values.redis.master.containerPorts.redis }}"
        command: 
        - sh
        - -c
        - |
          echo "Waiting for Redis at $REDIS_HOST:$REDIS_PORT..."
          until nc -z $REDIS_HOST $REDIS_PORT; do
            echo "Redis is not available yet. Retrying in 2 seconds..."
            sleep 2
          done
          echo "Redis is available. Proceeding with the main application container."
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: REDIS_HOST
              value: "{{ .Values.redis.fullnameOverride }}-master"
            - name: REDIS_PORT
              value: "{{ .Values.redis.master.containerPorts.redis }}"
            - name: REDIS_DB
              value: "{{ .Values.app.db }}"
            - name: PASSWORD_FILE_PATH
              value: "{{ .Values.app.passwordFilePath }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.containerPort }}
              protocol: TCP
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
