---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: redis-secret
spec:
  encryptedData:
    password: AgCcjUmKpGuYKeWT2rIKYjamk0IS1pmDt2WIggSYnomLsLU7eHmcgWWXJq8mXuUAEMv+SBMFHuJPEVBahsn5E8/POhIQdwH3fArqia8H35ozRGVPC6cuuJjEJnvBUqgBtNlBqp/R/Cmu9WNQfsCkY5Tkh+rMyzCXwSE+hkCvRGAJogDYQ1nawOP4AY8FjnreueqeTpTQxbtEPVznOHg1S07dUAVjFoJmIhtClHLM+XqQz8qOPMKqcWMAdLU0ivlBgRKrTzFZNdxgwp6Z7Sg4mQikMNDy/6yu1MoHMAqmmQu4unETWGpcM3ESG7/P7UJQJqsatEhk43lIIcoL+kC56dXvzeasPHEDfRrVkRfx6QD28/qcNgP+Z5WTS47U2WTSM/XGD0wLmwIrHHZjzjpNInOdUwTeNUbWYa1u7HWuiphl3u6Q2mTH2SKXm6oQtBMYjUeG2mD2gJAs8JpS4/4RH+2L40BCMyET3hWNPkfvAYc/LmBk/fu7QwVZDF4EfY9fwp9NjaY3uePE7kG2fiaCa46Si+82c6eEa+Ni9j/yhssQqvrZxgDTBd3l48nw0bk/samoKYWme0OcPDe0MkwNGowVkA4HWrHDlgs/BqkahRAp0SjQWRvCVQRTNdmIci09uZ0iNAFKNp4qSeVeH5FNgzc2MIpM0u5xTf+hmnQoQtzpKzk5zAej4c0srIlYzbk/I3iEK8EVvTA9ryxewjBF8nUY
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: redis-secret
