---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: redis-secret
spec:
  encryptedData:
    password: AgCwB+L3LxCkcSdcQNTCyjeMn7XD0mYjWeC/dIwYXEsp6abcPQEBGZhl+P17kObqNzgmlahyLfaaP25axJ9q3M/GwmjH6bKdw4ggqLRPWVhx0TmbKLxg4XM8R2QvjtrjEuWMcTenuJvwetLIUCat0tLYNhgiDkykFnE5BuH1Z1e0M3RX6LE8Pw/gSsGRdjGL/Bp6zuF4lQRKCRcvSy/v4jZsHfVW5fsqrx4rxxcFs9VyoijkqD3GHfwmPzlrwN3esZceqaS1UY0dkeMk6f0ESsX/dxw3CC/VcSSyrRMyDmQap3WazPjEPLf/Ij+wonhMNKaVlahRAtuAfNlk5ydiy5Xx4cmiRSU8dwBBSL3jlyFBUlifzfJyoY8B36tnZlc16qdkiU+vPjFtvhRX58m/u/XbdAjJygMu9l7waR6JqMbJjd5xXFBx/vwSkVH2VVMHLr34J6OKrVXWNtChbjEiOQkQ9xYqVRz442+1fu+mA6BpyTlO8ayhSnEwdX+MUiZgssuuqIXUXE6Hp/eDa7X65l0IGnSWNoirc4lCRnQMBHRuQkHsdBNtzWP7JbQbSKAImepY/WrV4tYg4FbSUCZ8lqB8/Ro9XfSJqSGc4BQH65fBpl/ASJKijkFibyok1UoZTA84bj1aE74LQG3zYUXk+jOSy0pHD1blhQ73nPO3WhmTEnHn2kfmdTwiSY2OtuOUnA8xT/WiZwPYvvvZGo/9Tgcb
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: redis-secret
