apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealedsecrets-deployer
  namespace: gateway
rules:
  - apiGroups: ["bitnami.com"]
    resources: ["sealedsecrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealedsecrets-deployer-binding
  namespace: gateway
subjects:
  - kind: User   # or Group, depending on how your access entry maps identity
    name: arn:aws:sts::656338545145:assumed-role/Kube-resources-deployer/GitHubActions
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sealedsecrets-deployer
  apiGroup: rbac.authorization.k8s.io