name: Build and push container image to github and dockerhub

permissions:
    packages: write
    contents: read
    actions: write
    id-token: write

on:
    push:
        branches:
        -   'main'
        paths:
        -   'core/**'
        -   'prod.Dockerfile'
        -   'uv.lock'
    workflow_dispatch:

jobs:
    github_release:
        name: Build and push container image to GitHub
        uses: ./.github/workflows/release.yml
        with:
            registry: 'ghcr.io'
            containerRegistry: '${{ github.repository }}'
            dockerfilePath: 'prod.Dockerfile'
            namespace: 'gateway'
        secrets:
            registryUsername: '${{ github.actor }}'
            registryPassword: '${{ secrets.GITHUB_TOKEN }}'

    docker_release:
        name: Build and push container image to DockerHub
        uses: ./.github/workflows/release.yml
        with:
            registry: 'docker.io'
            containerRegistry: 'mohitd13/gateway-rate-limiter'
            dockerfilePath: 'prod.Dockerfile'
            namespace: 'gateway'
        secrets:
            registryUsername: '${{ vars.DOCKER_USERNAME }}'
            registryPassword: '${{ secrets.DOCKERHUB_TOKEN }}'

    